# Generated by Django 4.0.3 on 2022-04-11 07:07

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recharge_plans', '0004_alter_plans_amount_alter_plans_validity'),
    ]

    operations = [
        migrations.CreateModel(
            name='recharge',
            fields=[
                ('number', models.IntegerField(max_length=10)),
                ('paid', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='recharge_plans.plans')),
            ],
        ),
    ]
