# Generated by Django 4.0.3 on 2022-04-11 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prepaid', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recharge',
            name='number',
            field=models.PositiveBigIntegerField(max_length=10),
        ),
    ]
