# Generated by Django 4.0.3 on 2022-04-10 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recharge_plans', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plans',
            old_name='ammount',
            new_name='amount',
        ),
    ]
