# Generated by Django 4.0.3 on 2022-04-10 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recharge_plans', '0003_alter_plans_amount_alter_plans_validity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plans',
            name='amount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='plans',
            name='validity',
            field=models.PositiveIntegerField(),
        ),
    ]
